version: '{build}'
image:
  - Ubuntu
  - macos
  - Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

configuration: Release

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-


      $prefix = "";
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        $prefix = $env:APPVEYOR_REPO_TAG_NAME.TrimStart("v");
        Update-AppveyorBuild -Version "$prefix";
      }
      else
      {
        $props = [xml](Get-Content Directory.Build.props);
        $prefix = $props.Project.PropertyGroup.VersionPrefix + "-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))";

        echo "Build: Full version is $prefix";
      }

     
    
nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  APPVEYOR_YML_DISABLE_PS_LINUX: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version_prefix: '${prefix}'

install:
  - cmd: dotnet restore redmine-net-api.sln

before_build:
  - cmd: dotnet --version

build:
  project: redmine-net-api.sln
  verbosity: minimal

after_build:
  - cmd: dotnet pack src\redmine-net-api\redmine-net-api.csproj --output artifacts

test: off

artifacts:
  - name: NuGet Packages
    path: ./artifacts/**/*.nupkg
  - name: NuGet Symbol Packages
    path: ./artifacts/**/*.snupkg
    
skip_commits:
  files:
    - '**/*.md'
    - '**/*.gif'
    - '**/*.png'
    - '**/*.yml'
    - LICENSE
    - tests/*

for:
  -
    matrix:
      only:
        - image: Ubuntu

    deploy:
      - provider: NuGet
        name: dev
        api_key:
          secure: fo+5VNPIRQ98jFPBZSd4SsOVyXEsTxnQ52VWTrg3sgH1GwGXhi70Q561eimlmRhy
        skip_symbols: true
        on:
          branch: master

      - provider: NuGet
        name: production
        api_key:
          secure: fo+5VNPIRQ98jFPBZSd4SsOVyXEsTxnQ52VWTrg3sgH1GwGXhi70Q561eimlmRhy
        skip_symbols: false
        on:
          branch: master
          APPVEYOR_REPO_TAG: true 