version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
# configuration: Release
install:
- cmd: nuget restore -verbosity detailed
build_script:
  - Msbuild.exe redmine-net20-api/redmine-net20-api.csproj /verbosity:minimal /p:BuildNetFX20=true 
  - Msbuild.exe redmine-net40-api/redmine-net40-api.csproj /verbosity:minimal /p:BuildNetFX40=true 
  - Msbuild.exe redmine-net40-api-signed/redmine-net40-api-signed.csproj /verbosity:minimal /p:BuildNetFX40=true
  - Msbuild.exe redmine-net45-api/redmine-net45-api.csproj /verbosity:minimal /p:BuildNetFX45=true
  - Msbuild.exe redmine-net45-api-signed/redmine-net45-api-signed.csproj /verbosity:minimal /p:BuildNetFX45=true
  - Msbuild.exe redmine-net451-api/redmine-net451-api.csproj /verbosity:minimal /p:BuildNetFX451=true
  - Msbuild.exe redmine-net451-api-signed/redmine-net451-api-signed.csproj /verbosity:minimal /p:BuildNetFX451=true
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
    - path: NuGet/*.nupkg
    
test: off
# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
cache:
  - packages -> **\packages.config
deploy:
- provider: NuGet
  api_key:
    secure: PojoRMfsSOFs1hOuvSMRfR4+icliUzEg5hzjFjNUO03akBmKjWf22To/DYxSlzd/
  skip_symbols: true

