version: '{build}'
image:
   - Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

configuration: Release

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - ps: git config --global core.autocrlf true

  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      $branch = @{ $true = $env:APPVEYOR_REPO_BRANCH; $false = $(git symbolic-ref --short -q HEAD) }[$env:APPVEYOR_REPO_BRANCH -ne $NULL];
      $revision = @{ $true = "{0:00000}" -f [convert]::ToInt32("0" + $env:APPVEYOR_BUILD_NUMBER, 10); $false = "local" }[$env:APPVEYOR_BUILD_NUMBER -ne $NULL];
      $suffix = @{ $true = ""; $false = "$($branch.Substring(0, [math]::Min(10,$branch.Length)))-$revision"}[$branch -eq "master" -and $revision -ne "local"];
      $commitHash = $($env:APPVEYOR_REPO_COMMIT.substring(0,7));
      $buildSuffix = @{ $true = "$($suffix)-$($commitHash)"; $false = "$($branch)-$($commitHash)" }[$suffix -ne ""];
      $versionSuffix = @{ $true = "--version-suffix=$($suffix)"; $false = ""}[$suffix -ne ""];
    
nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  APPVEYOR_YML_DISABLE_PS_LINUX: true

install:
  - ps: dotnet restore redmine-net-api.sln

before_build:
  - ps: dotnet --version

build_script:
  - ps: dotnet build redmine-net-api.sln -c Release --version-suffix=$buildSuffix

after_build:
  - ps: dotnet pack src\redmine-net-api\redmine-net-api.csproj -c Release --output .\artifacts --include-symbols --no-build $versionSuffix

test: off

artifacts:
  - name: NuGet Packages
    path: .\artifacts\**\*.nupkg
  - name: NuGet Symbol Packages
    path: .\artifacts\**\*.snupkg
    
skip_commits:
  files:
    - '**/*.md'
    - '**/*.gif'
    - '**/*.png'
    - '**/*.yml'
    - LICENSE
    - tests/*

for:
  -
    matrix:
      only:
        - image: Ubuntu

    deploy:
      - provider: NuGet
        name: dev
        api_key:
          secure: fo+5VNPIRQ98jFPBZSd4SsOVyXEsTxnQ52VWTrg3sgH1GwGXhi70Q561eimlmRhy
        skip_symbols: true
        on:
          branch: master

      - provider: NuGet
        name: production
        api_key:
          secure: fo+5VNPIRQ98jFPBZSd4SsOVyXEsTxnQ52VWTrg3sgH1GwGXhi70Q561eimlmRhy
        skip_symbols: true
        on:
          branch: master
          APPVEYOR_REPO_TAG: true 