name: .NET Core

on: [push]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT:  1
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet: [ '3.1.100' ]
    name: OS ${{ matrix.os }} - dotnet ${{ matrix.dotnet }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet
      run: dotnet build --configuration Release
